# Generated by Django 5.2.5 on 2025-08-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incipit", models.CharField(max_length=256)),
                (
                    "office_part",
                    models.CharField(
                        choices=[
                            (
                                "Missa",
                                [
                                    ("in", "Introitus"),
                                    ("ky", "Kyriale"),
                                    ("gr", "Graduale"),
                                    ("al", "Alleluia"),
                                    ("se", "Sequentia"),
                                    ("of", "Offertorium"),
                                    ("pr", "Praefationes in tono solemni"),
                                    ("co", "Communio"),
                                    ("tr", "Tractus"),
                                ],
                            ),
                            (
                                "Officium divinum",
                                [
                                    ("an", "Antiphona"),
                                    ("ca", "Canticum"),
                                    ("hy", "Hymnus"),
                                    ("rb", "Responsorium breve"),
                                    ("re", "Responsorium"),
                                ],
                            ),
                            (
                                "Cetera",
                                [
                                    ("or", "Toni Communes"),
                                    ("im", "Improperia"),
                                    ("ps", "Psalmus"),
                                    ("va", "Varia"),
                                ],
                            ),
                        ],
                        db_column="office-part",
                        max_length=16,
                    ),
                ),
                ("mode", models.CharField(max_length=8)),
                ("version", models.CharField(max_length=128)),
                ("gabc", models.TextField()),
                ("initial", models.IntegerField(default=1)),
                ("gabc_verses", models.TextField()),
                ("cantusid", models.CharField(max_length=32)),
                ("commentary", models.CharField(max_length=256)),
                ("transcriber", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "gregobase_chants",
                "ordering": ("incipit",),
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("year", models.IntegerField()),
                ("editor", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("caption", models.TextField()),
                ("pages", models.TextField()),
            ],
            options={
                "db_table": "gregobase_sources",
                "ordering": ("-year", "title"),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tag", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "gregobase_tags",
                "ordering": ("tag",),
            },
        ),
        migrations.CreateModel(
            name="ChantTag",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "chant_id",
                        "tag_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chant",
                    models.ForeignKey(
                        db_column="chant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scores.chant",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        db_column="tag_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scores.tag",
                    ),
                ),
            ],
            options={
                "db_table": "gregobase_chant_tags",
                "unique_together": {("chant", "tag")},
            },
        ),
        migrations.AddField(
            model_name="chant",
            name="tags",
            field=models.ManyToManyField(
                related_name="scores", through="scores.ChantTag", to="scores.tag"
            ),
        ),
        migrations.CreateModel(
            name="ChantSource",
            fields=[
                (
                    "chant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="chant_sources",
                        serialize=False,
                        to="scores.chant",
                    ),
                ),
                ("page", models.CharField(max_length=16)),
                ("sequence", models.IntegerField()),
                ("extent", models.IntegerField()),
                (
                    "source",
                    models.ForeignKey(
                        db_column="source",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chant_sources",
                        to="scores.source",
                    ),
                ),
            ],
            options={
                "db_table": "gregobase_chant_sources",
                "ordering": ("source", "page", "sequence"),
                "unique_together": {("chant", "source", "page")},
            },
        ),
        migrations.AddField(
            model_name="chant",
            name="sources",
            field=models.ManyToManyField(
                related_name="chants", through="scores.ChantSource", to="scores.source"
            ),
        ),
    ]
