# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128)),
                ('incipit', models.CharField(max_length=256)),
                ('initial', models.IntegerField()),
                ('office_part', models.CharField(choices=[('Missa', (('in', 'Introitus'), ('ky', 'Kyriale'), ('gr', 'Graduale'), ('al', 'Alleluia'), ('se', 'Sequentia'), ('of', 'Offertorium'), ('pr', 'Praefationes in tono solemni'), ('ps', 'Offertorium'), ('co', 'Communio'), ('tr', 'Tractus'))), ('Officium divinum', (('an', 'Antiphona'), ('ca', 'Canticum'), ('hy', 'Hymnus'), ('rb', 'Responsorium breve'), ('re', 'Responsorium'))), ('Cetera', (('or', 'Toni Communes'), ('im', 'Improperia'), ('va', 'Varia')))], db_column='office-part', max_length=16)),
                ('mode', models.CharField(max_length=8)),
                ('gabc', models.TextField()),
                ('gabc_verses', models.TextField()),
                ('transcriber', models.CharField(max_length=128)),
                ('commentary', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('incipit',),
                'db_table': 'gregobase_chants',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('editor', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('caption', models.TextField()),
                ('pages', models.TextField()),
            ],
            options={
                'ordering': ('-year', 'title'),
                'db_table': 'gregobase_sources',
            },
        ),
        migrations.CreateModel(
            name='ChantSource',
            fields=[
                ('chant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scores.Score')),
                ('page', models.CharField(max_length=16)),
                ('sequence', models.IntegerField()),
                ('extent', models.IntegerField()),
            ],
            options={
                'ordering': ('sequence',),
                'db_table': 'gregobase_chant_sources',
            },
        ),
        migrations.AddField(
            model_name='source',
            name='scores',
            field=models.ManyToManyField(through='scores.ChantSource', to='scores.Score'),
        ),
        migrations.AddField(
            model_name='chantsource',
            name='source',
            field=models.ForeignKey(db_column='source', on_delete=django.db.models.deletion.CASCADE, to='scores.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='chantsource',
            unique_together=set([('chant', 'source', 'page')]),
        ),
    ]
