language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
addons:
  mariadb: '10.0'
  apt:
    packages:
      - libmariadbclient-dev
script:
  - python manage.py test
env:
  global:
    - SECRET_KEY=not_really_secret_key_for_tests
    - DEBUG=true
    - DB_NAME=gregoplus
    - DB_USER=travis
    - DB_PASSWORD=
    - DB_HOST=localhost
